_default:
  1:
    name: unity
    path: test/unity
    reference: 60def109a7cfa90aafee6758e7a61c199b83ac4f
    remote_url: git@github.com:ThrowTheSwitch/Unity.git
travis:
  1:
    name: unity
    path: test/unity
    reference: 60def109a7cfa90aafee6758e7a61c199b83ac4f
    remote_url: git://github.com/ThrowTheSwitch/Unity.git
